---
- name: Automate Server Updates
  hosts: all
  become: yes
  tasks:
    - name: Update all packages on servers
      ansible.builtin.yum:  
        name: '*'
        state: latest

    - name: Get current date and time
      ansible.builtin.command: date
      register: current_date

    - name: Create a file with current date and time
      ansible.builtin.copy:
        content: "Run at: {{ current_date.stdout }}"
        dest: "/tmp/run_time.txt"